pikatsume/main_app/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', views.about, name='about'),
    path('pikabase/', views.pikabase_index, name='index'),
    path('pikabase/new/', views.new_pika, name='new_pika'),
    path('profile/', views.profile, name='profile'),
    path('accounts/signup', views.signup, name='signup')
]

pikatsume/pikatsume/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main_app.urls')),
]

pikatsume/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
ORIGIN = (
    ('A', 'Anime'),
    ('G', 'Game'),
    ('F', 'Fan-made'),
)
class Ptype(models.Model):
    pika_type = models.CharField(max_length=100)
    
    def __str__(self):
        return self.pika_type

class Pika(models.Model):
    name = models.CharField(max_length=255)
    pic_url = models.CharField(max_length=500)
    pika_type = models.ManyToManyField(Ptype)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Origin(models.Model):
    origin = models.CharField(
        max_length=1,
        choices=ORIGIN,
        default=ORIGIN[0][0]
    )
    pika = models.ForeignKey(Pika, on_delete=models.CASCADE)

    def __str__(self):
        return self.get_origin_display()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

pikatsume/main_app/forms.py
from django import forms
from .models import Pika, Profile

class PikaForm(forms.ModelForm):
    class Meta:
        model = Pika
        fields = ('name', 'pic_url')

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
        # fields = ('user_id','id')

pikatsume/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.dispatch import receiver
from .models import Pika, Ptype, Profile
from .forms import PikaForm
# Create your views here.

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('profile')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = { 'form' : form, 'error_message' : error_message }
    return render(request, 'registration/signup.html', context)

def home(request):
    return render(request, 'home')

def about(request):
    return  render(request, 'about')

def pikabase_index(request):
    pikas = Pika.objects.all()
    return  render(request, 'pikabase/index.html', { 'pikas': pikas })

@login_required
def profile(request):
    return render(request, 'accounts/profile')

@login_required
def new_pika(request):
    if request.method == 'POST':
        new_form = PikaForm(request.POST)
        if new_form.is_valid():
            pika = new_form.save(commit="False")
            pika.user = request.user
            pika.save()
            return redirect ('pikabase/index.html', pika.id)
    else:
        new_form = PikaForm()
        context = {  'new_form' : new_form  }
        return render(request, 'pikabase/pika_form.html', context)

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile.html')
    else:
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'profile.html', {'profile_form': profile_form})

pikatsume/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About PikAtsume</h1>
    <h4>A collection of Pikachus!</h4>
    <h3>Pikatsume?</h3>
    <p>Atsume (集め, あつめ) = Japanese word for "Collecting"</p>
    <p>Pika(ピカ) = For Pikachu, duh.</p>
{% endblock %}

pikatsume/main_app/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    <h1>Profile</h1>
    <h4>Hello, {{ user.username }}!</h4>
    {% comment %} <form method="post">
        {% csrf_token %}
        {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
</form> {% endcomment %}
{% endblock %}

pikatsume/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>(o^.^o)Pikatsume!</title>
    <!-- CSS -->
    <link href="https://fonts.googleapis.com/css?family=Mouse+Memoirs|Inter:200,300,400,500,600,700,800,900&display=swap"" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
  <body>
      <header class="navbar-fixed">
          <nav>
            <div class="nav-wrapper">
              <ul>
                <li><a href="/" class="left brand-logo bold">Pikatsume!</a></li>
              </ul>
              <ul class="right">
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'index' %}">View the Pikabase</a></li>
                {% if user.is_authenticated %}
                  <li><a href="{% url 'new_pika' %}">Add a Pikachu</a></li>
                  <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                  <li><a href="{% url 'signup' %}">Sign Up</a></li>
                  <li><a href="{% url 'login' %}">Log In</a></li>
                {% endif %}
               </ul>
            </div>
          </nav>
      </header>
      <main class="container">
          {% block content %}
          {% endblock %}
      </main>
      <footer>&copy; 2020 Pika Pika</footer>
  </body>
</html>

pikatsume/main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>(o^.^o)Pikatsume!</title>
    <!-- CSS -->
    <link href="https://fonts.googleapis.com/css?family=Mouse+Memoirs|Inter:200,300,400,500,600,700,800,900&display=swap"" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <!-- JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
    <section class="section">
        <div class="container">
           
            <div class="content">
                 <img class="is-pulled-left" src="https://i.ibb.co/vdtqnDx/solo-upsetti-chu-bg.png" alt="A Pikachu" />
                <h1 class="title is-1">Pikatsume!</h1>
                <h3 class="subtitle is-3">A Collection of Pikachus</h3>
            <section class="section">
                <a href="{% url 'index' %}" class="home-btn button"><i class="fas fa-bolt"></i>&nbsp; View the Pikabase</a>
                <a href="{% url 'signup' %}" class="home-btn button"><i class="fas fa-bolt"></i>&nbsp; Sign Up</a>
                <a href="{% url 'login' %}" class="home-btn button"><i class="fas fa-bolt"></i>&nbsp; Log In</a>
                <br />
                <span class="smol-text is-pulled-right">
                    Pikachu by <a href="https://twitter.com/rizuNM/media" class="bold" target="_blank">rizuNM</a>
                </span>
            </section>

        </div>
    </section>
</body>
</html>

pikatsume/main_app/templates/pikabase/index.html
{% extends 'base.html' %}
{% block content %}
  <h2>The Pikabase!</h2>
  <div class="row">
    {% for pika in pikas %}
    <div class="col s5 m5 l5">

      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
        <img class="responsive-img" src="{{ pika.pic_url }}" alt="A Pikachu">
      </div>
      <div class="card-content">
        <h4>{{ pika.name }}</h4>
        {% for origin in pika.origin_set.all %}
          <p><span class="bold">Origin:</span> {{ origin.get_origin_display }}</p> 
        {% endfor %}
        <p><span class="bold">Type:</span>
          <ul class="pika-list">
            {% for pika in pika.pika_type.all %}      
              <li>
                <span>
                  <i class="fas fa-bolt"></i>
                </span> {{ pika.pika_type }}
              </li>
            {% endfor %}
          </ul>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
  <!-- Add Pika Form -->
{% endblock %}

pikatsume/main_app/templates/pikabase/pika_form.html
{% extends 'base.html' %}

{% block content %}
    <section class="form-section">
        <h1>Add a Pikachu</h1>
        <form  method="POST" class="artist-form">
            {% csrf_token %}
            {{new_form.as_p}}
            {{type_form.as_p}}
            <button class="btn" type="submit">Save</button>
        </form>
    </section>
{% endblock %}

pikatsume/main_app/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <h1>Profile</h1>
    <h4>Hello, {{ user }}!</h4>
{% endblock %}